### ISSUE TITLE
Document SQL SA password

### ISSUE THREAD

**Issue by DannyMeister** [gusztavvargadr/infrastructure#9]
I had to search through your source quite a while to find what the sa password for SQL Server was.  Maybe some basic documentation on critical usability aspects such as credentials could be added to the workstation repo or on Vagrant Cloud.  It would save a lot of time for those like me who are just pulling your vagrant cloud boxes for productivity and aren't using your whole packer infrastructure to customize boxes of my own.

**Comment by gusztavvargadr** [comment]
@DannyMeister I'm sorry for the inconvenience, but glad to hear you've found it at least [in the sources](https://github.com/gusztavvargadr/infrastructure/blob/4018bb033a6fd9ffd3c3224d6603397c7bc6c9a8/src/components/sql/chef/cookbooks/gusztavvargadr_sql/files/2014.ini#L131).

I did not document the SA password as the SQL Server boxes are supposed to work with the [vagrant user with Windows Authentication](https://github.com/gusztavvargadr/infrastructure/blob/4018bb033a6fd9ffd3c3224d6603397c7bc6c9a8/src/components/sql/chef/cookbooks/gusztavvargadr_sql/files/2014.ini#L126), which can be used to create any other users, but you're right that then at least this should be mentioned on Vagrant Cloud as well. I'll close this in favor of https://github.com/gusztavvargadr/packer/issues/77 which you can use for tracking the progress if interested.

I hope you otherwise like using the box(es), indeed, my goal with publishing them was to encourage others to use them on their own (otherwise I would not have bothered building them for weeks and uploading TBs of data on a 20 Mb/s uplink :) Please [let me know](https://github.com/gusztavvargadr/packer/issues) if you have any other feedback or requests. In the meantime, thanks for understanding that my resources are limited and sometimes I make mistakes as well :)

Btw, I also accept PRs for all the repos mentioned, documentation included :)

**Comment by DannyMeister** [comment]
Agreed that Windows Auth is generally the way to go, and that has worked well for me up to this point.  I've hit an oddball application which doesn't support using Windows Auth during its setup.

Using your boxes has been a wonderful productivity boost for me, thank you very much! :)  I hope at some point I do have the opportunity to contribute in a way more substantial that providing feedback.
